### ISSUE TITLE
[Feat]: Create Login System

### ISSUE THREAD

**Issue by balaji-sivasakthi** [amanjaiman1/Product_3D#29]
### Feature Description
I would like to request the addition of a new feature to the login system. The proposed feature is as follows:

### Feature Name: Social Media Login Integration

The feature involves integrating social media login functionality. This would allow users to sign in to their accounts using their social media credentials, such as Google, Github instead of creating a separate account with a username and password.

I would like to contribute under GSSOC'23, assign to me

**Comment by amanjaiman1** [comment]
Let's do it men

**Comment by Athiban2002** [comment]
Hey, I am also interested to work on this issue with him @balaji-sivasakthi and I would like to work with him, so please assign it to me under GSSOC. Let's work together.

**Comment by balaji-sivasakthi** [comment]
That's great! @Athiban2002.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by amanjaiman1** [comment]
Go ahead guys

**Comment by amanjaiman1** [comment]
Who is seriousely working on this issue ?
See i have to assign one of you according to rules but i assigned you all three , now let me know who is completing and i have to set a timeline through which you have to complete your contribution.
otherwise sorry guys i have to unassign you

@balaji-sivasakthi @senthil-k8s @syedawanya18

**Comment by balaji-sivasakthi** [comment]
Hello @amanjaiman1 , I would appreciate some clarification on the process for my work. Currently, I am working on creating the schema and controllers for storing customers tshirt design and track their order. Furthermore, I am planning to incorporate both Google authentication and custom email/password authentication.

**Comment by amanjaiman1** [comment]
Good going , keep up this gratitude.
thanks for  updation

**Comment by senthil-k8s** [comment]
Sorry for the Delay guys, since I'm not aware of the message. Currently, I am working on the login system page

### Feature Overview:
The feature aims to allow users to log in using their social media accounts instead of creating separate credentials. It provides convenience and streamlines the login process.

### Implementation Steps:

1. Integrate OAuth protocols: Implementing the OAuth protocol to connect with social media platforms like Facebook, Google, or Twitter.
2. Redirect to authorization pages: When users choose the social media login option, redirect them to the respective platform's authorization page.
3. Obtain and store access tokens: Upon user authorization, retrieve and securely store access tokens, which allow the application to access the user's social media account.
4. Retrieve profile information: Using the access tokens to retrieve the user's profile information from the social media platform's API.
5. Link accounts and database management: Create or update user accounts in the application's database based on the retrieved profile information, ensuring proper account linking and management.

**Comment by amanjaiman1** [comment]
Implement Login & SignUp page through Firebase. @balaji-sivasakthi @creator79 @senthil-k8s

**Comment by JTtime** [comment]
@senthil-k8s Important opinion on Your point number 2 of implementation steps

On successful login, redirecting to authorization pages should adopt conditional rendering method. I have seen many projects where people are simply redirecting to authorization pages like

If baseURL/LoginPage changes LoggedIn state, then it will redirect to baseURL/Products or something else. With this login system, anyone can get access to baseURL/products by simply typing URI. Which defeats the purpose of login System.

**Comment by amanjaiman1** [comment]
> @senthil-k8s Important opinion on Your point number 2 of implementation steps
> 
> On successful login, redirecting to authorization pages should adopt conditional rendering method. I have seen many projects where people are simply redirecting to authorization pages like
> 
> If baseURL/LoginPage changes LoggedIn state, then it will redirect to baseURL/Products or something else. With this login system, anyone can get access to baseURL/products by simply typing URI. Which defeats the purpose of login System.

Discuss this issue on our Team Discord Server

**Comment by balaji-sivasakthi** [comment]
@JTtime @amanjaiman1 
I've completed the redux state management for user. 

> Additionally, I created a component for testing the state by using updateUser Reducer and  dispatch it in test/user.test.js 

`GET /test`

### Before the state update
----------------------------
![1](https://github.com/amanjaiman1/Product_3D/assets/65065614/b543d2ed-727f-4f28-a5dd-7efd8fe62bd8)

![2](https://github.com/amanjaiman1/Product_3D/assets/65065614/c19784a0-ff92-4d2c-a177-fcb125d9c295)

### After the state update
----------------------------
![4](https://github.com/amanjaiman1/Product_3D/assets/65065614/26b6a2f5-3b6e-48a7-9267-9a50ff6a7ee3)

![4](https://github.com/amanjaiman1/Product_3D/assets/65065614/f09005f7-4341-4de0-bcb1-e806c4c1b14b)
